# Generated by Django 5.1.3 on 2024-11-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_category_description_alter_genre_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
