# Generated by Django 5.1.3 on 2024-11-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_category_description_remove_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default='', verbose_name='Дата виходу'),
        ),
    ]
