# Generated by Django 5.1.3 on 2024-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='world_premiere',
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
