# Generated by Django 5.1.3 on 2024-11-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_budget_remove_movie_world_premiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Постер'),
        ),
    ]
