# Generated by Django 5.1.3 on 2024-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=500, null=True, verbose_name='Постер'),
        ),
    ]
