# Generated by Django 5.1.3 on 2024-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_genres_alter_movie_url_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='', verbose_name='Постер'),
        ),
    ]
