# Generated by Django 5.1.3 on 2024-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='', max_length=200, verbose_name='Постер'),
        ),
    ]
