# Generated by Django 5.1.3 on 2024-11-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
    ]
